# Site
name: "N33rdZ"
title: "N33rdZ"
description: "N33rdZ"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /Blog
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: n33rdzz@gmail.com

# Authors
authors:
  Heidi:
    name: Heidi
    display_name: Heidi
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/donate/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  Alya:
    name: Alya
    display_name: Alya   
    avatar: 'assets/images/aleyya.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: 123456789@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/coreflood_
    description: ":D:D"
  Neroli:
    name: Neroli
    display_name: Neroli  
    avatar: 'assets/images/neroli.jpg'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: alyyaser12@gmail.com
    web: https://neroli-realy.github.io/
    Linkedin: https://www.linkedin.com/in/yasser-ali-264884143/
    description: "Software Developer and penetration tester, I love CTf's and Problem solving and doing bughunting in free time."
  Flex:
    name: Flex
    display_name: Flex   
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
